### ISSUE TITLE
Where does the pixel art get saved?

### ISSUE THREAD

**Issue by SpoopWoop** [GDColon/GD-Pixel-Art#9]
I know I'm stupid but I just can't find where the pixel art actually get saved to pls help :3

**Comment by grave36** [comment]
It creates a new level with the image inside it.

**Comment by SpoopWoop** [comment]
But that does not happen for me, I have looked through all levels and there is no art :(

**Comment by hashtag-2992** [comment]
Try using a .jpg image.

**Comment by bopditybran** [comment]
> Try using a .jpg image.

jpg images dont work either

**Comment by GDColon** [comment]
It should appear as your most recent GD level.
If not, edit line 15 of the code so that it matches the directory of your GD save file
(by default it's /AppData/Local/GeometryDash/CCLocalLevels.dat)

**Comment by bopditybran** [comment]
> It should appear as your most recent GD level.
> If not, edit line 15 of the code so that it matches the directory of your GD save file
> (by default it's /AppData/Local/GeometryDash/CCLocalLevels.dat)
> 
> btw this doesn't work on mac

thank you colon, bow down to him
